
package br.udesc.modulo1.view;

/**
 *
 * @author nando
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form Application
     */
    public TelaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        itemSite = new javax.swing.JMenu();
        itemTermo = new javax.swing.JMenu();
        itemNoticia = new javax.swing.JMenu();
        consultarTitulo = new javax.swing.JMenuItem();
        consultarLink = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RSS Manager");

        jMenuBar1.setBackground(new java.awt.Color(102, 153, 255));
        jMenuBar1.setToolTipText("");
        jMenuBar1.setName(""); // NOI18N

        itemSite.setText("Site");
        jMenuBar1.add(itemSite);

        itemTermo.setText("Termos");
        jMenuBar1.add(itemTermo);

        itemNoticia.setText("Noticias");

        consultarTitulo.setText("Consultar o titulo");
        consultarTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarTituloActionPerformed(evt);
            }
        });
        itemNoticia.add(consultarTitulo);

        consultarLink.setText("Consultar o link");
        consultarLink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarLinkActionPerformed(evt);
            }
        });
        itemNoticia.add(consultarLink);

        jMenuBar1.add(itemNoticia);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void consultarTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_consultarTituloActionPerformed

    private void consultarLinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarLinkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_consultarLinkActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenuItem consultarLink;
    public javax.swing.JMenuItem consultarTitulo;
    private javax.swing.JMenu itemNoticia;
    private javax.swing.JMenu itemSite;
    private javax.swing.JMenu itemTermo;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
